version: 0.2

phases: 
  install:
    commands:
      # Install Node
      - echo Installing Node 14...
      - curl -sL https://deb.nodesource.com/setup_14.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      #install dependencies
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      #build
      - echo Building...
      - npm run AWS-build
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: frontend/build