version: 0.2

phases: 
  install:
    commands:
      # Install Node
      - curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -
      - yum -y install nodejs
  pre_build:
    commands:
      #install dependencies
      - npm install
  build:
    commands:
      #build
      - npm run AWS-build
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: frontend/build